/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import Object.Coach;
import Object.CoachInfo;
import Object.Participant;
import Object.ParticipantInfo;
import Object.Team;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;

/**
 *
 * @author Tamim-PC
 */
public class AdminModule extends javax.swing.JFrame {

    HashMap<String, Participant> allParticipantInfo;
    HashMap<String, Coach> allCoachInfo;
    HashMap<String, Team> allTeamInfo;
    
    public AdminModule() {
        setupFrame();
    }
    public AdminModule(HashMap<String, Participant> PartInfo , HashMap<String, Coach> CoachInfo, HashMap<String, Team> teamInfo){
        allParticipantInfo = new HashMap<String, Participant>();
        allParticipantInfo.putAll(PartInfo);
        
        ///added
        allCoachInfo= new HashMap<String, Coach> ();
        allCoachInfo.putAll(CoachInfo);
        
        allTeamInfo = new HashMap<String, Team> ();
        allTeamInfo.putAll(teamInfo);
        
        setupFrame();
    }
    public void setupFrame(){
        initComponents();
        this.setSize(1366,768);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        
        this.addWindowListener(new WindowAdapter() 
        {
            public void windowClosing(WindowEvent evt) {
                try
                {
                    int opt = JOptionPane.showConfirmDialog(null, "Do you want to Exit?","Close",JOptionPane.YES_NO_OPTION);
                    if(opt == 0) {
                        ParticipantInfo PI = new ParticipantInfo(allParticipantInfo);
                        PI.writeData();
                     
                        CoachInfo ci = new CoachInfo(allCoachInfo);
                        ci.writeData();
                        System.exit(0);
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Oops! There are some problems!", "Unknown Error Occured!", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        });
    }
    void renderAllTable(){
        
    }
    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    public static boolean isValidMobile(String mobile) 
    { 
        String mobileRegex = "^(\\+\\d{1,3}( )?)?((\\(\\d{3}\\))|\\d{3})[- .]?\\d{3}[- .]?\\d{4}$" 
	      + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?){2}\\d{3}$" 
	      + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?)(\\d{2}[ ]?){2}\\d{2}$";
        Pattern pat = Pattern.compile(mobileRegex); 
        if (mobile == null) 
            return false; 
        return pat.matcher(mobile).matches(); 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        participntPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        participantTableScrollPane = new javax.swing.JScrollPane();
        participantTable = new javax.swing.JTable();
        profilePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        handleLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        unilabel = new javax.swing.JLabel();
        tshirtLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        coachesPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        universityPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        slotDistPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        participantsButton = new javax.swing.JLabel();
        coachesButton = new javax.swing.JLabel();
        universityButton = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        slotDistributionButton = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });
        searchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTextFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchTextFieldMouseExited(evt);
            }
        });
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 83, 240, 40));

        participntPanel.setOpaque(false);
        participntPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Participants");
        participntPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 310, 70));

        participantTableScrollPane.setOpaque(false);

        participantTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        participantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "University", "Handle ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        participantTable.setColumnSelectionAllowed(true);
        participantTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        participantTable.setOpaque(false);
        participantTable.setRowHeight(40);
        participantTable.setRowMargin(1);
        participantTable.getTableHeader().setResizingAllowed(false);
        participantTable.getTableHeader().setReorderingAllowed(false);
        participantTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                participantTableMouseClicked(evt);
            }
        });
        participantTableScrollPane.setViewportView(participantTable);
        participantTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        participntPanel.add(participantTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 770, -1));

        jTabbedPane1.addTab("tab3", participntPanel);

        profilePanel.setOpaque(false);
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Profile");
        profilePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 160, 40));

        emailLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Set Text");
        profilePanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 440, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Handle ID        :");
        profilePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Full Name        :");
        profilePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Date of Birth   :");
        profilePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Contact            :");
        profilePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("University        :");
        profilePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 140, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("Address            :");
        profilePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 140, 30));

        handleLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        handleLabel.setForeground(new java.awt.Color(255, 255, 255));
        handleLabel.setText("Set Text");
        profilePanel.add(handleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 440, 30));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 255));
        jLabel13.setText("Email                :");
        profilePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, 30));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 255));
        jLabel14.setText("Gender             :");
        profilePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 140, 30));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 255));
        jLabel15.setText("T-Shirt              :");
        profilePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 140, 30));

        dobLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(255, 255, 255));
        dobLabel.setText("Set Text");
        profilePanel.add(dobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 440, 30));

        contactLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactLabel.setText("Set Text");
        profilePanel.add(contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 440, 30));

        genderLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Set Text");
        profilePanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 440, 30));

        unilabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        unilabel.setForeground(new java.awt.Color(255, 255, 255));
        unilabel.setText("Set Text");
        profilePanel.add(unilabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 440, 30));

        tshirtLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        tshirtLabel.setForeground(new java.awt.Color(255, 255, 255));
        tshirtLabel.setText("Set Text");
        profilePanel.add(tshirtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 440, 30));

        addressLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Set Text");
        profilePanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 440, 30));

        nameLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Set Text");
        profilePanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 440, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/profile.png"))); // NOI18N
        profilePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jTabbedPane1.addTab("tab2", profilePanel);

        coachesPanel.setOpaque(false);
        coachesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("Coaches");
        coachesPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 230, 60));

        jTabbedPane1.addTab("tab1", coachesPanel);

        universityPanel.setOpaque(false);
        universityPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("University");
        universityPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 290, 60));

        jTabbedPane1.addTab("tab3", universityPanel);

        slotDistPanel.setOpaque(false);
        slotDistPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Slot Distribution");
        slotDistPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 400, 70));

        jTabbedPane1.addTab("tab5", slotDistPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -30, 940, 820));

        jScrollPane2.setAutoscrolls(true);

        searchList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        searchList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        searchList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchList.setOpaque(false);
        searchList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchListKeyPressed(evt);
            }
        });
        searchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                searchListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(searchList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 240, 60));

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, -1));

        participantsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/admin/participantsButton_1.png"))); // NOI18N
        participantsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                participantsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                participantsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                participantsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                participantsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                participantsButtonMouseReleased(evt);
            }
        });
        getContentPane().add(participantsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        coachesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/admin/coachesButton_1.png"))); // NOI18N
        coachesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coachesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coachesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coachesButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coachesButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                coachesButtonMouseReleased(evt);
            }
        });
        getContentPane().add(coachesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        universityButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/admin/universityButton_1.png"))); // NOI18N
        universityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                universityButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                universityButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                universityButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                universityButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                universityButtonMouseReleased(evt);
            }
        });
        getContentPane().add(universityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/admin/LogOutButton_1.png"))); // NOI18N
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutButtonMouseReleased(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, -1));

        slotDistributionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/admin/slotDistributionButton_1.png"))); // NOI18N
        slotDistributionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotDistributionButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slotDistributionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slotDistributionButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slotDistributionButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slotDistributionButtonMouseReleased(evt);
            }
        });
        getContentPane().add(slotDistributionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/participantModuleBG.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // TODO add your handling code here:
        jScrollPane2.setVisible(false);
        searchList.removeAll();
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void searchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldMouseClicked

    private void searchTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextFieldMouseEntered
        // TODO add your handling code here
    }//GEN-LAST:event_searchTextFieldMouseEntered

    private void searchTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldMouseExited

    private void searchTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if(searchList.getSelectedIndex() >= 0){
                searchTextField.setText(searchList.getSelectedValue());
            }
        }
    }//GEN-LAST:event_searchTextFieldKeyPressed

    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
        // TODO add your handling code here:
        CharSequence s = searchTextField.getText().toString().trim();
        if(s.length()<1)
        {
            jScrollPane2.setVisible(false);
            searchList.removeAll();
            return;
        }
        Vector<String> list = new Vector<String>();
        for(String str : allParticipantInfo.keySet()) {
            if(str.contains(s)){
                list.add(str);
            }
        }
        searchList.setListData(list);
        if(list.size()>=1){
            searchList.setSelectedIndex(0);
            jScrollPane2.setVisible(true);
        }
        else{
            jScrollPane2.setVisible(false);
            searchList.removeAll();
        }
    }//GEN-LAST:event_searchTextFieldKeyReleased

    private void searchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_searchTextFieldKeyTyped

    private void searchListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchListKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchListKeyPressed

    private void searchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_searchListValueChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_searchListValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void participantsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantsButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(participntPanel);
    }//GEN-LAST:event_participantsButtonMouseClicked

    private void coachesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachesButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(coachesPanel);
    }//GEN-LAST:event_coachesButtonMouseClicked

    private void universityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(universityPanel);
    }//GEN-LAST:event_universityButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Do you want to Log out?","Close",JOptionPane.YES_NO_OPTION);
        if(opt == 0) {
            this.setVisible(false);
            HomeFrame home = new HomeFrame(allParticipantInfo, allCoachInfo, allTeamInfo);
            home.setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void slotDistributionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotDistributionButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(slotDistPanel);
    }//GEN-LAST:event_slotDistributionButtonMouseClicked

    private void participantsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantsButtonMouseEntered
        // TODO add your handling code here:
        participantsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/participantsButton_2.png")));
    }//GEN-LAST:event_participantsButtonMouseEntered

    private void participantsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantsButtonMouseExited
        // TODO add your handling code here:
         participantsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/participantsButton_1.png")));
    }//GEN-LAST:event_participantsButtonMouseExited

    private void participantsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantsButtonMousePressed
        // TODO add your handling code here:
         participantsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/participantsButton_3.png")));
    }//GEN-LAST:event_participantsButtonMousePressed

    private void participantsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantsButtonMouseReleased
        // TODO add your handling code here:
         participantsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/participantsButton_2.png")));
    }//GEN-LAST:event_participantsButtonMouseReleased

    private void coachesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachesButtonMouseEntered
        // TODO add your handling code here:
       coachesButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/coachesButton_2.png")));
    }//GEN-LAST:event_coachesButtonMouseEntered

    private void coachesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachesButtonMouseExited
        // TODO add your handling code here:
        coachesButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/coachesButton_1.png")));
    }//GEN-LAST:event_coachesButtonMouseExited

    private void coachesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachesButtonMousePressed
        // TODO add your handling code here:
        coachesButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/coachesButton_3.png")));
    }//GEN-LAST:event_coachesButtonMousePressed

    private void coachesButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachesButtonMouseReleased
        // TODO add your handling code here:
        coachesButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/coachesButton_2.png")));
    }//GEN-LAST:event_coachesButtonMouseReleased

    private void universityButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityButtonMouseEntered
        // TODO add your handling code here:
        universityButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/universityButton_2.png")));
    }//GEN-LAST:event_universityButtonMouseEntered

    private void universityButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityButtonMouseExited
        // TODO add your handling code here:
        universityButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/universityButton_1.png")));
    }//GEN-LAST:event_universityButtonMouseExited

    private void universityButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityButtonMousePressed
        // TODO add your handling code here:
        universityButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/universityButton_3.png")));
    }//GEN-LAST:event_universityButtonMousePressed

    private void universityButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityButtonMouseReleased
        // TODO add your handling code here:
        universityButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/universityButton_2.png")));
    }//GEN-LAST:event_universityButtonMouseReleased

    private void slotDistributionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotDistributionButtonMouseEntered
        // TODO add your handling code here:
        slotDistributionButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/slotDistributionButton_2.png")));
    }//GEN-LAST:event_slotDistributionButtonMouseEntered

    private void slotDistributionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotDistributionButtonMouseExited
        // TODO add your handling code here:
        slotDistributionButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/slotDistributionButton_1.png")));
    }//GEN-LAST:event_slotDistributionButtonMouseExited

    private void slotDistributionButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotDistributionButtonMousePressed
        // TODO add your handling code here:
        slotDistributionButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/slotDistributionButton_3.png")));
    }//GEN-LAST:event_slotDistributionButtonMousePressed

    private void slotDistributionButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotDistributionButtonMouseReleased
        // TODO add your handling code here:
        slotDistributionButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/slotDistributionButton_2.png")));
    }//GEN-LAST:event_slotDistributionButtonMouseReleased

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        logoutButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/LogOutButton_2.png")));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here: 
        logoutButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/LogOutButton_1.png")));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMousePressed
        // TODO add your handling code here:
         logoutButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/LogOutButton_3.png")));
    }//GEN-LAST:event_logoutButtonMousePressed

    private void logoutButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseReleased
        // TODO add your handling code here:
         logoutButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/admin/LogOutButton_2.png")));
    }//GEN-LAST:event_logoutButtonMouseReleased

    private void participantTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participantTableMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        int column = source.columnAtPoint( evt.getPoint() );
        String s=source.getModel().getValueAt(row, column)+"";
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_participantTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel coachesButton;
    private javax.swing.JPanel coachesPanel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel handleLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTable participantTable;
    private javax.swing.JScrollPane participantTableScrollPane;
    private javax.swing.JLabel participantsButton;
    private javax.swing.JPanel participntPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JList<String> searchList;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel slotDistPanel;
    private javax.swing.JLabel slotDistributionButton;
    private javax.swing.JLabel tshirtLabel;
    private javax.swing.JLabel unilabel;
    private javax.swing.JLabel universityButton;
    private javax.swing.JPanel universityPanel;
    // End of variables declaration//GEN-END:variables
}
