package Module;


import Module.HomeFrame;
import Object.Participant;
import java.io.*;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import Object.ParticipantInfo;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.regex.Pattern;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author splash365 <tamim.365.ti at gmail.com>
 */
public class RegistrationFrame extends javax.swing.JFrame {

    HashMap<String, Participant> allParticipantInfo;
    
    public RegistrationFrame() {
        setupFrame();
    }
    
    public RegistrationFrame(HashMap<String, Participant> Info){
        allParticipantInfo = new HashMap<String, Participant>();
        allParticipantInfo.putAll(Info);
        setupFrame();
    }
    
    public void setupFrame(){
        initComponents();
        this.setSize(1366,768);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registration");
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() 
        {
            public void windowClosing(WindowEvent evt) {
                try
                {
                    int opt = JOptionPane.showConfirmDialog(null, "Do you want to Exit?","Close",JOptionPane.YES_NO_OPTION);
                    if(opt == 0) 
                    {
                        ParticipantInfo PI = new ParticipantInfo(allParticipantInfo);
                        PI.writeData();
                        System.exit(0);
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Oops! There are some problems!", "Unknown Error Occured!", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        });
    }
    
    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    public static boolean isValidMobile(String mobile) 
    { 
        String mobileRegex = "^(\\+\\d{1,3}( )?)?((\\(\\d{3}\\))|\\d{3})[- .]?\\d{3}[- .]?\\d{4}$" 
	      + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?){2}\\d{3}$" 
	      + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?)(\\d{2}[ ]?){2}\\d{2}$";
        Pattern pat = Pattern.compile(mobileRegex); 
        if (mobile == null) 
            return false; 
        return pat.matcher(mobile).matches(); 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        participantNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        participantEmailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        participantHandleIdTextField = new javax.swing.JTextField();
        participantMobileTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        participantUniversityTextField = new javax.swing.JTextField();
        participantMonthComboBox = new javax.swing.JComboBox<>();
        participantYearComboBox = new javax.swing.JComboBox<>();
        participantDayComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        participantGenderComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        participantPresentAddressTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        participantPasswordField = new javax.swing.JPasswordField();
        participantTshirtComboBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        emailCheckLabel = new javax.swing.JLabel();
        handleCheckLabel = new javax.swing.JLabel();
        mobileCheckLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        coachNameTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        coachEmailTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        coachHandleIdTextField1 = new javax.swing.JTextField();
        coachMobileTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        coachUniversityTextField1 = new javax.swing.JTextField();
        coachMonthComboBox1 = new javax.swing.JComboBox<>();
        coachYearComboBox1 = new javax.swing.JComboBox<>();
        coachDayComboBox1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        coachGenderComboBox1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coachPresentAddressTextArea1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        coachPasswordField = new javax.swing.JPasswordField();
        coachTshirtComboBox = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/home/participantButton_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/home/coachButton_1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/home/backButton_1.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, -1, -1));

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        participantNameTextField.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        participantNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        participantNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(participantNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 320, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Full Name                  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, 30));

        participantEmailTextField.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        participantEmailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        participantEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                participantEmailTextFieldFocusLost(evt);
            }
        });
        participantEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantEmailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(participantEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 320, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email Address           :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Handle Id                   :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 190, 30));

        participantHandleIdTextField.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        participantHandleIdTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        participantHandleIdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                participantHandleIdTextFieldFocusLost(evt);
            }
        });
        participantHandleIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantHandleIdTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(participantHandleIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 320, 30));

        participantMobileTextField.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        participantMobileTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        participantMobileTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                participantMobileTextFieldFocusLost(evt);
            }
        });
        participantMobileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantMobileTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(participantMobileTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 320, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mobile No.                 :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 190, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("University/College     :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 190, 30));

        participantUniversityTextField.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        participantUniversityTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        participantUniversityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantUniversityTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(participantUniversityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 320, 30));

        participantMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        participantMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantMonthComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(participantMonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 100, 30));

        participantYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        participantYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantYearComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(participantYearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 100, 30));

        participantDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));
        jPanel1.add(participantDayComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 100, 30));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date of Birth               :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 190, 30));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender                        :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 190, 30));

        participantGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        participantGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantGenderComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(participantGenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Present Address         :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 190, 30));

        participantPresentAddressTextArea.setColumns(20);
        participantPresentAddressTextArea.setRows(3);
        participantPresentAddressTextArea.setTabSize(4);
        participantPresentAddressTextArea.setToolTipText("");
        participantPresentAddressTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(participantPresentAddressTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 320, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/participantBanner.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 440, 90));

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Choose a Password    :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 190, 30));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 140, 50));
        jPanel1.add(participantPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 320, -1));

        participantTshirtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "S", "M", "L", "XL", "XXL" }));
        participantTshirtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantTshirtComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(participantTshirtComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 110, 30));

        jLabel25.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("T-shirt  :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 80, 30));

        emailCheckLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailCheckLabel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(emailCheckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 210, 30));

        handleCheckLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        handleCheckLabel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(handleCheckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 210, 30));

        mobileCheckLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mobileCheckLabel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(mobileCheckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 210, 30));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coachNameTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        coachNameTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        coachNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachNameTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 320, 30));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Full Name                  :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, 30));

        coachEmailTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        coachEmailTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        coachEmailTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachEmailTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachEmailTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 320, 30));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email Address           :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, 30));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Position                       :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 190, 30));

        coachHandleIdTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        coachHandleIdTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        coachHandleIdTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachHandleIdTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachHandleIdTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 320, 30));

        coachMobileTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        coachMobileTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        coachMobileTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachMobileTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachMobileTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 320, 30));

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mobile No.                 :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 190, 30));

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("University/College     :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 190, 30));

        coachUniversityTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        coachUniversityTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        coachUniversityTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachUniversityTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachUniversityTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 320, 30));

        coachMonthComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        coachMonthComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachMonthComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachMonthComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 100, 30));

        coachYearComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        coachYearComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachYearComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachYearComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 100, 30));

        coachDayComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));
        jPanel2.add(coachDayComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 100, 30));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Date of Birth               :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 190, 30));

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gender                        :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 190, 30));

        coachGenderComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        coachGenderComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachGenderComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(coachGenderComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 30));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Present Address         :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 190, 30));

        coachPresentAddressTextArea1.setColumns(20);
        coachPresentAddressTextArea1.setRows(5);
        coachPresentAddressTextArea1.setTabSize(4);
        coachPresentAddressTextArea1.setToolTipText("");
        coachPresentAddressTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(coachPresentAddressTextArea1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 320, 80));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/coachBanner.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 90));

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("T-shirt  :");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 80, 30));
        jPanel2.add(coachPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 320, -1));

        coachTshirtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "S", "M", "L", "XL", "XXL" }));
        coachTshirtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachTshirtComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(coachTshirtComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 110, 30));

        jLabel27.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Choose a Password    :");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 190, 30));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 140, 50));

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -30, 990, 800));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/loginRegistrationBackground.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void participantNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantNameTextFieldActionPerformed

    private void participantEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantEmailTextFieldActionPerformed

    private void participantHandleIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantHandleIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantHandleIdTextFieldActionPerformed

    private void participantMobileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantMobileTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantMobileTextFieldActionPerformed

    private void participantUniversityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantUniversityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantUniversityTextFieldActionPerformed

    private void participantYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantYearComboBoxActionPerformed
        // TODO add your handling code here:
        participantDayComboBox.removeAllItems();
        participantDayComboBox.addItem("Day");
        String[] days_31 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
        String[] days_30 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"};
        String[] days_29 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"};
        String[] days_28 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"};
        String year = participantYearComboBox.getSelectedItem().toString();
        String month = participantMonthComboBox.getSelectedItem().toString();
        if(year.equals("Year") != true && month.equals("Month") != true) {
            int yearValue = Integer.parseInt(year);
            boolean leap = false;
            if (((yearValue % 4 == 0) && (yearValue % 100!= 0)) || (yearValue%400 == 0)) leap = true;
            if(month.equals("January") || month.equals("March") || month.equals("May") || month.equals("July") || month.equals("August") || month.equals("October") || month.equals("December")) {
                participantDayComboBox.removeAllItems();
                for(String s : days_31) participantDayComboBox.addItem(s);
            }
            else if(month.equals("April") || month.equals("June") || month.equals("September") || month.equals("November")) {
                participantDayComboBox.removeAllItems();
                for(String s : days_30) participantDayComboBox.addItem(s);
            }
            else if(month.equals("February")) {
                participantDayComboBox.removeAllItems();
                if(leap) 
                    for(String s : days_29) participantDayComboBox.addItem(s);
                else for(String s : days_28) participantDayComboBox.addItem(s);
            }
        }
    }//GEN-LAST:event_participantYearComboBoxActionPerformed

    private void participantMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantMonthComboBoxActionPerformed
        // TODO add your handling code here:
        participantDayComboBox.removeAllItems();
        participantDayComboBox.addItem("Day");
        String[] days_31 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
        String[] days_30 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"};
        String[] days_29 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"};
        String[] days_28 = {"Day","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"};
        String year = participantYearComboBox.getSelectedItem().toString();
        String month = participantMonthComboBox.getSelectedItem().toString();
        if(year.equals("Year") != true && month.equals("Month") != true) {
            int yearValue = Integer.parseInt(year);
            boolean leap = false;
            if (((yearValue % 4 == 0) && (yearValue % 100!= 0)) || (yearValue%400 == 0)) leap = true;
            if(month.equals("January") || month.equals("March") || month.equals("May") || month.equals("July") || month.equals("August") || month.equals("October") || month.equals("December")) {
                participantDayComboBox.removeAllItems();
                for(String s : days_31) participantDayComboBox.addItem(s);
            }
            else if(month.equals("April") || month.equals("June") || month.equals("September") || month.equals("November")) {
                participantDayComboBox.removeAllItems();
                for(String s : days_30) participantDayComboBox.addItem(s);
            }
            else if(month.equals("February")) {
                participantDayComboBox.removeAllItems();
                if(leap) 
                    for(String s : days_29) participantDayComboBox.addItem(s);
                else for(String s : days_28) participantDayComboBox.addItem(s);
            }
        }
    }//GEN-LAST:event_participantMonthComboBoxActionPerformed

    private void participantGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantGenderComboBoxActionPerformed

    private void coachNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachNameTextField1ActionPerformed

    private void coachEmailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachEmailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachEmailTextField1ActionPerformed

    private void coachMobileTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachMobileTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachMobileTextField1ActionPerformed

    private void coachUniversityTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachUniversityTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachUniversityTextField1ActionPerformed

    private void coachMonthComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachMonthComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachMonthComboBox1ActionPerformed

    private void coachYearComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachYearComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachYearComboBox1ActionPerformed

    private void coachGenderComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachGenderComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachGenderComboBox1ActionPerformed

    private void coachHandleIdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachHandleIdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachHandleIdTextField1ActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        HomeFrame home = new HomeFrame(allParticipantInfo);
        home.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            // TODO add your handling code here:
            String participantName = participantNameTextField.getText().toString(); 
            String participantEmail = participantEmailTextField.getText().toString();
            String participantHandleId = participantHandleIdTextField.getText().toString();
            String participantMobile = participantMobileTextField.getText().toString();
            String participantUniversity = participantUniversityTextField.getText().toString();
            String DOBYear = participantYearComboBox.getSelectedItem().toString();
            String DOBMonth = participantMonthComboBox.getSelectedItem().toString();
            String DOBDay = participantDayComboBox.getSelectedItem().toString();
            String participantDOB = DOBDay+"-"+DOBMonth+"-"+DOBYear;
            String participantGender = participantGenderComboBox.getSelectedItem().toString();
            String participantTshirt = participantTshirtComboBox.getSelectedItem().toString();
            String participantPresentAddress = participantPresentAddressTextArea.getText().toString();
            String participantPassword = new String(participantPasswordField.getPassword());
            
            Participant P = new Participant(participantName,participantEmail, participantHandleId, participantMobile, participantUniversity, participantDOB, participantGender, participantTshirt, participantPresentAddress, participantPassword);
            
//            ParticipantInfo pt = new ParticipantInfo();
//            pt.add(P);
            
            int opt = JOptionPane.showConfirmDialog(null, "Do you want to Submit?","Confirmation",JOptionPane.YES_NO_OPTION);
            if(opt == 0) 
            {
//                pt.writeData();
                allParticipantInfo.put(participantHandleId, P);
                
                participantNameTextField.setText("");
                participantEmailTextField.setText("");
                participantHandleIdTextField.setText("");
                participantMobileTextField.setText("");
                participantPasswordField.setText("");
                participantUniversityTextField.setText("");
                participantGenderComboBox.setSelectedIndex(0);
                participantYearComboBox.setSelectedIndex(0);
                participantMonthComboBox.setSelectedIndex(0);
                participantDayComboBox.setSelectedIndex(0);
                participantTshirtComboBox.setSelectedIndex(0);
                participantPresentAddressTextArea.setText("");
                JOptionPane.showMessageDialog(null, "Registration Successful");
            }
        }
//        catch (HeadlessException | IOException e){
//            JOptionPane.showMessageDialog(null, "Registration Failed! Try again later..", "DataBase I/O Error", JOptionPane.ERROR_MESSAGE);
//        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Registration Failed! Try again later..", "DataBase Element Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void participantTshirtComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantTshirtComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantTshirtComboBoxActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/participantButton_2.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/participantButton_1.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/participantButton_3.png")));
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/participantButton_2.png")));
    }//GEN-LAST:event_jLabel1MouseReleased

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
        backButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/backButton_2.png")));
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        backButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/backButton_1.png")));
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMousePressed
        // TODO add your handling code here:
        backButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/backButton_3.png")));
    }//GEN-LAST:event_backButtonMousePressed

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
        // TODO add your handling code here:
        backButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/backButton_2.png")));
    }//GEN-LAST:event_backButtonMouseReleased

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/coachButton_2.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/coachButton_3.png")));
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/coachButton_1.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/coachButton_2.png")));
    }//GEN-LAST:event_jLabel2MouseReleased

    private void coachTshirtComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachTshirtComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachTshirtComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void participantEmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_participantEmailTextFieldFocusLost
        // TODO add your handling code here:
        String email = participantEmailTextField.getText().toString();
        if(!isValid(email)){
            emailCheckLabel.setText("Invalid Email Address!");
        }
        else 
            emailCheckLabel.setText("");
    }//GEN-LAST:event_participantEmailTextFieldFocusLost

    private void participantHandleIdTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_participantHandleIdTextFieldFocusLost
        // TODO add your handling code here:
        String handle = participantHandleIdTextField.getText().toString();
        ParticipantInfo PI = new ParticipantInfo(allParticipantInfo);
        if(PI.isValid(handle)) handleCheckLabel.setText("Handle Id Already Exists!");
        else handleCheckLabel.setText("");
    }//GEN-LAST:event_participantHandleIdTextFieldFocusLost

    private void participantMobileTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_participantMobileTextFieldFocusLost
        // TODO add your handling code here:
        String mobile = participantMobileTextField.getText().toString();
        if(!isValidMobile(mobile)) mobileCheckLabel.setText("Invalid Mobile No!");
        else mobileCheckLabel.setText("");
    }//GEN-LAST:event_participantMobileTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JComboBox<String> coachDayComboBox1;
    private javax.swing.JTextField coachEmailTextField1;
    private javax.swing.JComboBox<String> coachGenderComboBox1;
    private javax.swing.JTextField coachHandleIdTextField1;
    private javax.swing.JTextField coachMobileTextField1;
    private javax.swing.JComboBox<String> coachMonthComboBox1;
    private javax.swing.JTextField coachNameTextField1;
    private javax.swing.JPasswordField coachPasswordField;
    private javax.swing.JTextArea coachPresentAddressTextArea1;
    private javax.swing.JComboBox<String> coachTshirtComboBox;
    private javax.swing.JTextField coachUniversityTextField1;
    private javax.swing.JComboBox<String> coachYearComboBox1;
    private javax.swing.JLabel emailCheckLabel;
    private javax.swing.JLabel handleCheckLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mobileCheckLabel;
    private javax.swing.JComboBox<String> participantDayComboBox;
    private javax.swing.JTextField participantEmailTextField;
    private javax.swing.JComboBox<String> participantGenderComboBox;
    private javax.swing.JTextField participantHandleIdTextField;
    private javax.swing.JTextField participantMobileTextField;
    private javax.swing.JComboBox<String> participantMonthComboBox;
    private javax.swing.JTextField participantNameTextField;
    private javax.swing.JPasswordField participantPasswordField;
    private javax.swing.JTextArea participantPresentAddressTextArea;
    private javax.swing.JComboBox<String> participantTshirtComboBox;
    private javax.swing.JTextField participantUniversityTextField;
    private javax.swing.JComboBox<String> participantYearComboBox;
    // End of variables declaration//GEN-END:variables
}
