
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author splash365 <tamim.365.ti at gmail.com>
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1080,720);
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("NCPC 2021");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventDetailsButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        eventDetailsButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eventDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eventDetailsButton_2.png"))); // NOI18N
        eventDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventDetailsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventDetailsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventDetailsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eventDetailsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eventDetailsButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(eventDetailsButton)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(eventDetailsButton)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventDetailsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonMouseEntered
        // TODO add your handling code here:
        eventDetailsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/eventDetailsButton_1.png")));
    }//GEN-LAST:event_eventDetailsButtonMouseEntered

    private void eventDetailsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonMouseExited
        // TODO add your handling code here:
        eventDetailsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/eventDetailsButton_2.png")));
    }//GEN-LAST:event_eventDetailsButtonMouseExited

    private void eventDetailsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonMousePressed
        // TODO add your handling code here:
        eventDetailsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/eventDetailsButton_3.png")));
    }//GEN-LAST:event_eventDetailsButtonMousePressed

    private void eventDetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eventDetailsButtonMouseClicked

    private void eventDetailsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonMouseReleased
        // TODO add your handling code here:
        eventDetailsButton.setIcon(new ImageIcon(getClass().getResource("/images/buttons/eventDetailsButton_1.png")));
    }//GEN-LAST:event_eventDetailsButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventDetailsButton;
    // End of variables declaration//GEN-END:variables
}
