
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author splash365 <tamim.365.ti at gmail.com>
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1080,720);
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("NCPC 2021");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventDetailsButtonTwo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        eventDetailsButtonTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/home/eventDetailsButton_1.png"))); // NOI18N
        eventDetailsButtonTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eventDetailsButtonTwoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eventDetailsButtonTwoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eventDetailsButtonTwoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eventDetailsButtonTwoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(eventDetailsButtonTwo)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(eventDetailsButtonTwo)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventDetailsButtonTwoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonTwoMouseEntered
        // TODO add your handling code here:
        eventDetailsButtonTwo.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/eventDetailsButton_2.png")));
    }//GEN-LAST:event_eventDetailsButtonTwoMouseEntered

    private void eventDetailsButtonTwoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonTwoMouseExited
        // TODO add your handling code here:
        eventDetailsButtonTwo.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/eventDetailsButton_1.png")));
    }//GEN-LAST:event_eventDetailsButtonTwoMouseExited

    private void eventDetailsButtonTwoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonTwoMousePressed
        // TODO add your handling code here:
        eventDetailsButtonTwo.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/eventDetailsButton_3.png")));
    }//GEN-LAST:event_eventDetailsButtonTwoMousePressed

    private void eventDetailsButtonTwoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventDetailsButtonTwoMouseReleased
        // TODO add your handling code here:
        eventDetailsButtonTwo.setIcon(new ImageIcon(getClass().getResource("/images/buttons/home/eventDetailsButton_2.png")));
    }//GEN-LAST:event_eventDetailsButtonTwoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventDetailsButtonTwo;
    // End of variables declaration//GEN-END:variables
}
